on:
  workflow_call:
    inputs:
      terraform_version:
        type: string
        description: "Terraform version to use"
        required: true
      terraform_working_directory:
        type: string
        description: "Path to the terraform configuration"
        default: "./"
      terraform_lockfile:
        type: string
        description: "Path to the terraform lock file"
        default: '.terraform.lock.hcl'
      terraform_parallelism:
        type: string
        description: "Terraform concurrent API calls"
        default: "20"
      terraform_backend_config_file:
        type: string
        description: "The terraform backend-config file path"
        required: true
      terraform_var_file:
        type: string
        description: "The Terraform var-file file path"
        required: true
      terraform_action:
        type: string
        description: "Whether to plan or apply"
        required: true
      auto_approve:
        type: string
        description: "If we are approving manually rather than via PR"
        default: "false"
      tflint_version:
        type: string
        description: "The version of TFLint to run."
        default: "v0.58.1"
      tflint_severity:
        type: string
        description: "Which severity will TFLint fail on, one of error, warning and notice."
        default: "warning"
      tfsec_version:
        type: string
        description: "The version of tfsec to run."
        default: "v1.28.13"
      aws_federated_role_name:
        type: string
        description: "The IAM Role name GitHub will obtain credentials for using OIDC"
        default: "GitHubActionsInfra"
      aws_assumed_role_name:
        type: string
        description: "The IAM Role name GitHub will obtain credentials for by assuming as the federated IAM Role"
        default: "terraform-admin"
      aws_account_id:
        type: string
        description: "The AWS Account ID we will authenticate against to run these terraform actions"
        required: true
      aws_region:
        type: string
        description: "The AWS Region we will run these terraform actions against"
        required: true
    secrets:
      terraform_pat:
        required: true

jobs:
  plan:
    runs-on: ubuntu-latest
    name: Terraform ${{ inputs.terraform_action }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TERRAFORM_HTTP_CREDENTIALS: |
        github.com/infratask2company=github:${{ secrets.terraform_pat }}
    steps:
      - name: Checkout
        # actions/checkout@v4
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - name: Configure federated AWS Credentials
        # uses: aws-actions/configure-aws-credentials@v4
        uses: aws-actions/configure-aws-credentials@a03048d87541d1d9fcf2ecf528a4a65ba9bd7838
        with:
          audience: sts.amazonaws.com
          aws-region: ${{ inputs.aws_region }}
          role-to-assume: arn:aws:iam::${{ inputs.aws_account_id }}:role/${{ inputs.aws_federated_role_name }}
          role-skip-session-tagging: true

      - name: Configure assumed AWS Credentials
        # uses: aws-actions/configure-aws-credentials@v4
        uses: aws-actions/configure-aws-credentials@a03048d87541d1d9fcf2ecf528a4a65ba9bd7838
        with:
          aws-region: ${{ inputs.aws_region }}
          role-to-assume: arn:aws:iam::${{ inputs.aws_account_id }}:role/${{ inputs.aws_assumed_role_name }}
          role-chaining: true

      - id: "gcp-auth"
        name: Configure Google Cloud Credentials
        # uses: google-github-actions/auth@v1
        uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093
        with:
          workload_identity_provider: projects/123456789012/locations/global/workloadIdentityPools/github-action-identity-pool/providers/github-action-id-provider
          service_account: terraform@identity-123456.iam.gserviceaccount.com

      - name: Cache Terraform Plugins
        # uses: actions/cache@v4
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830
        with:
          path: ${{ runner.temp }}/_github_home/.terraform.d/plugin-cache
          key: ${{ runner.os }}-tf-${{ hashFiles(inputs.terraform_lockfile) }}

      - name: Terraform-docs - fail on diff
        uses: terraform-docs/gh-actions@6de6da0cefcc6b4b7a5cbea4d79d97060733093c
        with:
          working-dir: ${{ inputs.terraform_working_directory }}
          config-file: ${{ inputs.terraform_working_directory }}.terraform-docs.yml
          fail-on-diff: true

          # use the config file values
          output-method:
          output-file:
          output-format:
          template:

      - name: TFLint - setup
        uses: terraform-linters/setup-tflint@4cb9feea73331a35b422df102992a03a44a3bb33
        with:
          tflint_version: ${{ inputs.tflint_version }}

      - name: TFLint - run
        env:
            # https://github.com/terraform-linters/tflint/blob/master/docs/user-guide/plugins.md#avoiding-rate-limiting
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          tflint --version
          tflint --init
          # Remove the last character of the working directory for tflint, as the trailing '/' doesn't raise failures when it should do
          TFLINT_PATH=`echo ${{ inputs.terraform_working_directory }} | sed 's/.\{1\}$//'`
          tflint -f compact --chdir=$TFLINT_PATH --minimum-failure-severity=${{ inputs.tflint_severity }} --recursive

      - name: Terraform - check format
        # uses: dflook/terraform-fmt-check@v1
        uses: dflook/terraform-fmt-check@10eaa13fa61437aa51be2d12fafe95f152e3512d
        with:
          path: ${{ inputs.terraform_working_directory }}
          backend_config_file: ${{ inputs.terraform_backend_config_file }}

      - name: Terraform - validate
        # uses: dflook/terraform-validate@v1
        uses: dflook/terraform-validate@03889814f1c6cf2fea714787218b2f4edc85c369
        with:
          path: ${{ inputs.terraform_working_directory }}
          backend_config_file: ${{ inputs.terraform_backend_config_file }}

      - name: Terraform - plan
        # uses: dflook/terraform-plan@v1
        uses: dflook/terraform-plan@dc251c444763eed5defd065b866874b6343017ca
        if: ${{ inputs.terraform_action == 'plan' }}
        env:
          TERRAFORM_PRE_RUN: |
            # required by terraform to authenticate against EKS
            pip3 install awscli --no-cache-dir --break-system-packages
        with:
          path: ${{ inputs.terraform_working_directory }}
          var_file: ${{ inputs.terraform_var_file }}
          backend_config_file: ${{ inputs.terraform_backend_config_file }}
          parallelism: ${{ inputs.terraform_parallelism }}

      - name: Terraform - apply
        #uses: dflook/terraform-apply@v1
        uses: dflook/terraform-apply@8f47d0ad9f3cb9e50fd6b3595c0cb98f00c518df
        if: ${{ inputs.terraform_action == 'apply' }}
        env:
          TERRAFORM_PRE_RUN: |
            # required by terraform to authenticate against EKS
            pip3 install awscli --no-cache-dir --break-system-packages
        with:
          path: ${{ inputs.terraform_working_directory }}
          var_file: ${{ inputs.terraform_var_file }}
          backend_config_file: ${{ inputs.terraform_backend_config_file }}
          parallelism: ${{ inputs.terraform_parallelism }}
          auto_approve: ${{ inputs.auto_approve }}
