name: terraform-pullrequest

on:
  pull_request:
    paths:
      - "*.tf"
      - "modules/**"
      - "terraform/modules/**"
      - "var-files/*.tfvars"
      - "backend-configs/*.tfbackend"
      - ".github/workflows/terraform-action.yaml"
      - ".github/workflows/terraform-pullrequest.yaml"
      - ".github/workflows/terraform-merge.yaml"

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  tf-plan-test:
    strategy:
      fail-fast: false
      matrix:
        account_env: [
          "test"
        ]
        account: [
          { name: "main",     id: "1111111111", region: "eu-west-1"},
          { name: "customer", id: "2222222222", region: "eu-west-1"}
        ]
    if: github.event_name == 'pull_request' # plan test on pull request
    uses: ./.github/workflows/terraform-action.yaml
    concurrency:
      group: ci-${{ matrix.account.id }}
      cancel-in-progress: false
    with:
      terraform_version: ${{ vars.TERRAFORM_VERSION }}
      terraform_working_directory: ${{ vars.TERRAFORM_WORKING_DIRECTORY }}
      terraform_lockfile: ${{ vars.TERRAFORM_LOCKFILE }}
      terraform_parallelism: ${{ vars.TERRAFORM_PARALLELISM }}
      terraform_backend_config_file: backend-configs/workloads.${{ matrix.account_env }}.${{ matrix.account.name }}.tfbackend
      terraform_var_file: var-files/workloads.${{ matrix.account_env }}.${{ matrix.account.name }}.tfvars
      terraform_action: plan
      aws_account_id: ${{ matrix.account.id }}
      aws_region: ${{ matrix.account.region }}
    secrets:
      terraform_pat: ${{ secrets.TERRAFORM_PAT }}

  tf-plan-staging:
    strategy:
      matrix:
        account_env: [
          "staging"
        ]
        account: [
          { name: "main",     id: "3333333333", region: "eu-west-1"},
        ]
    if: false #github.event_name == 'pull_request' 
    uses: ./.github/workflows/terraform-action.yaml
    concurrency:
      group: ci-${{ matrix.account.id }}
      cancel-in-progress: false
    with:
      terraform_version: ${{ vars.TERRAFORM_VERSION }}
      terraform_working_directory: ${{ vars.TERRAFORM_WORKING_DIRECTORY }}
      terraform_lockfile: ${{ vars.TERRAFORM_LOCKFILE }}
      terraform_parallelism: ${{ vars.TERRAFORM_PARALLELISM }}
      terraform_backend_config_file: backend-configs/workloads.${{ matrix.account_env }}.${{ matrix.account.name }}.tfbackend
      terraform_var_file: var-files/workloads.${{ matrix.account_env }}.${{ matrix.account.name }}.tfvars
      terraform_action: plan
      aws_account_id: ${{ matrix.account.id }}
      aws_region: ${{ matrix.account.region }}
    secrets:
      terraform_pat: ${{ secrets.TERRAFORM_PAT }}


  tf-plan-prod:
    strategy:
      fail-fast: false
      matrix:
        account_env: [
          "prod"
        ]
        account: [
          { name: "main", id: "5555555555", region: "eu-west-1"},
          { name: "partner1", id: "1234567890", region: "eu-west-1"},
          { name: "partner2", id: "2234567890", region: "eu-west-1"},
          { name: "partner3", id: "3234567890", region: "eu-west-1"},
          { name: "partner4", id: "4234567890", region: "eu-west-1"}
        ]
    if: github.event_name == 'pull_request' # plan prod on pull request
    uses: ./.github/workflows/terraform-action.yaml
    concurrency:
      group: ci-${{ matrix.account.id }}
      cancel-in-progress: false
    with:
      terraform_version: ${{ vars.TERRAFORM_VERSION }}
      terraform_working_directory: ${{ vars.TERRAFORM_WORKING_DIRECTORY }}
      terraform_lockfile: ${{ vars.TERRAFORM_LOCKFILE }}
      terraform_parallelism: ${{ vars.TERRAFORM_PARALLELISM }}
      terraform_backend_config_file: backend-configs/workloads.${{ matrix.account_env }}.${{ matrix.account.name }}.tfbackend
      terraform_var_file: var-files/workloads.${{ matrix.account_env }}.${{ matrix.account.name }}.tfvars
      terraform_action: plan
      aws_account_id: ${{ matrix.account.id }}
      aws_region: ${{ matrix.account.region }}
    secrets:
      terraform_pat: ${{ secrets.TERRAFORM_PAT }}
